### ISSUE TITLE
회원 가입 페이지

### ISSUE THREAD

**Issue by prayinforrain** [boostcampwm-2022/web34-moheyum#32]
- [x] 레이아웃 작성
- [x] 아이디, 비밀번호, 비밀번호 확인, 닉네임, 이메일을 입력할 수 있어야 한다.
- [x] 이메일 인증 코드를 위한 입력 필드도 구현하되 실제 기능은 넣지 않는다. (Week 3 예정)
- [x] 회원가입 버튼을 누르면 입력 필드들을 검증하고 유효하면 서버에 요청을 보낸다.
- [x] 유효하지 않은 입력이 있을 경우 해당 필드 아래에 붉은 색으로 안내 메시지를 표시한다. (?)
  - 토스트 메시지로 띄울지? 아니면 각 필드 밑에 안내할지?

**Comment by namhyo01** [comment]
# FE와 맞춘 세부 설계
1. ID : 특수문자 X, 한글 X, 4~16 바이트
2. PW : 영문 소,대, 특수문자 중 2개 이상 포함하고 6~16 바이트
3. nickname : 특수문자 X, 1~16 바이트

**Comment by prayinforrain** [comment]
![image](https://user-images.githubusercontent.com/46566891/201933593-6c243221-53f8-4cc2-8dc3-0fcde4fa928e.png)
https://github.com/boostcampwm-2022/web34-moheyum/commit/e68f6ed82e40b382d712fd9e5eb5318250f81e64 으로 입력 필드 검증까지 구현하였음.  
  
### 자동완성 스타일 지정
![image](https://user-images.githubusercontent.com/46566891/201933512-5d82b0e2-1a75-41e4-a195-62eb79f0d6b6.png)  
위 사진같이 크롬 자동완성으로 채워진 `input` 엘리먼트는 푸른색 배경화면이 적용되는 문제가 있음.  
이를 `autofill` 선택자를 통해 `background-color`가 아닌 `box-shadow` 프로퍼티를 통해 제어해야 한다고 함.. 이유는 잘 나와있는 레퍼런스가 없음
```css
&:-webkit-autofill,
  &:-webkit-autofill:hover,
  &:-webkit-autofill:focus,
  &:-webkit-autofill:active {
    -webkit-box-shadow: 0 0 0 30px white inset !important;
  }
```
